### ISSUE TITLE
Data about reconstruction result

### ISSUE THREAD

**Issue by xiankun1995** [wsh312/S2Dnet#1]
伍世浩老师您好！
很抱歉打扰您，我是西北工业大学的一名研二学生。不知您是否方便提供一些S2Dnet转换后的图像的重建结果给我。
谢谢您的开源~

**Comment by wsh312** [comment]
Hi, thanks for the suggestion, some reconstruction results of S2Dnet are
uploaded to Git.

Cheers,
Shihao

xiankun1995 <notifications@github.com> 于2019年1月10日周四 上午3:21写道：

**Comment by xiankun1995** [comment]
Thank you very much!

**Comment by xiankun1995** [comment]
I'm sorry to disturb you again. 
could you share the camera pose of synthetic data with me?
Thank you very much!
